### ISSUE TITLE
platformize-oasis在微信小程序中渲染gltf模型发黑

### ISSUE THREAD

**Issue by xyt0110** [deepkolos/platformize#10]
直接运行example里面的`oasis-wechat`，在模拟器上显示正常，在`ios真机`上加载的gltf都显示成黑色

![gltf 模型](https://static.xiaocloud.tech/images/WechatIMG67.jpeg)

**Comment by deepkolos** [comment]
@xyt0110 只在ios出现么

**Comment by alw-AYs** [comment]
好像是从2.24.4版本开始的，把版本推到了2.24.1就正常，我看微信更新日志里有一个canvas优化

**Comment by deepkolos** [comment]
@alw-AYs 上周六找到问题了, 是texSubImage2D 这个api挂了导致, 代码已打patch
