### ISSUE TITLE
platformize-pixi中pixijs升到6.4.2会报一个TextMetrics的错

### ISSUE THREAD

**Issue by laallan** [deepkolos/platformize#11]
查了一下pixi的源码，是TextMetrics._canvas，他6.3.0后的版本改成了双下线
private static __canvas: HTMLCanvasElement | OffscreenCanvas;
private static __context: CanvasRenderingContext2D | OffscreenCanvasRenderingContext2D;

**Comment by deepkolos** [comment]
@laallan 不支持无缝升级哈, 需要一个版本一个版本适配😂
