### ISSUE TITLE
In the WeChat applet, both OBJLoader and GLTFloader (other loads have not been tried) cannot monitor the loading progress. Other than that, everything is normal. Has anyone else encountered this situation?

### ISSUE THREAD

**Issue by 632366134** [deepkolos/platformize#12]
In the WeChat applet, both OBJLoader and GLTFloader (other loads have not been tried) cannot monitor the loading progress. Other than that, everything is normal. Has anyone else encountered this situation?

**Comment by 632366134** [comment]
in "three-platformize": "1.133.2"

**Comment by deepkolos** [comment]
@632366134 yes in wechat [`wx.request`](https://developers.weixin.qq.com/miniprogram/dev/api/network/request/wx.request.html), no `progress` keyword can be found
