### ISSUE TITLE
给obj模型添加材质时出现ar背景反复镜像的问题

### ISSUE THREAD

**Issue by 632366134** [deepkolos/platformize#13]
![QQ截图20220905113102](https://user-images.githubusercontent.com/50910792/188355412-667ca2be-746c-438b-8ac7-23ae57c290e6.png)

https://user-images.githubusercontent.com/50910792/188355785-465916a7-3eb7-40cc-99e3-f6d2e082de2f.mp4

**Comment by deepkolos** [comment]
背景是如何绘制呢?

**Comment by 632366134** [comment]
> 背景是如何绘制呢?

https://github.com/wechat-miniprogram/miniprogram-demo/tree/master/miniprogram/packageAPI/pages/ar/2dmarker-ar
根据小程序官方ar识别示例提供代码绘制的，里面的yuvBehavior.js有webgl代码我看不是很懂

**Comment by 632366134** [comment]
https://developers.weixin.qq.com/s/nmS2X2mA7XCL
这是代码片段，大佬有没有什么解决方案可以指点一下

> 背景是如何绘制呢?

**Comment by datased2019** [comment]
@632366134 你这个问题搞定了吗？刚看了一下微信YUV绘制的代码，需要使用到OES_vertex_array_object扩展，但是Platformize是明确不支持的。 @deepkolos  有什么建议吗？谢谢！

**Comment by deepkolos** [comment]
@datased2019  vao 只是一个优化扩展, 可有可无, 不影响渲染, 应该不是这个扩展导致问题

**Comment by deepkolos** [comment]
@632366134 看代码是老的three-platformize , 我这边尝试了并没有复现, 估计是微信marker模型训练效果提升了?


https://user-images.githubusercontent.com/12824616/221132139-b1c82891-3ca1-4446-b03b-9f968632c207.mp4
