### ISSUE TITLE
微信更新后，pixi下的序列帧案例ios下跑不了了

### ISSUE THREAD

**Issue by cailven** [deepkolos/platformize#14]
模拟器是好的，ios下报错

![微信图片_20220905185238](https://user-images.githubusercontent.com/4739001/188432648-9ef5f11a-ea99-4c99-a890-f389bcabd455.jpg)

**Comment by cailven** [comment]
源码里好几个都爆这个错误，好像都是json文件的那些。微信版本8.0.27

**Comment by deepkolos** [comment]
@cailven 基础库版本是多少

**Comment by cailven** [comment]
> @cailven 基础库版本是多少

2,26.0

**Comment by deepkolos** [comment]
估计是 是loader的资源判断有问题, 刚应该修了, 可以试试

https://github.com/deepkolos/platformize/blob/main/packages/platformize-pixi/plugin/plugin-platformize.ts#L68
