### ISSUE TITLE
能适配字节小程序真机吗？

### ISSUE THREAD

**Issue by mmotiy** [deepkolos/platformize#17]

**Comment by deepkolos** [comment]
之前字节小程序关闭了普通用户webgl通道就没跟进了, 没有审核过的账号去调试

**Comment by mmotiy** [comment]
现在不需要审核了,我找了其他的pixijs的兼容版本,但是发现微信小程序环境可以load 声音,但是字节小程序不行

**Comment by deepkolos** [comment]
@mmotiy 声音还没测, 绘制应该ok了, 可以尝试下

https://github.com/deepkolos/platformize/tree/main/examples/pixi-byte

https://user-images.githubusercontent.com/12824616/221129404-36a6df64-0ba2-4839-881e-fcae5e09051f.mp4

**Comment by mmotiy** [comment]
牛啊牛啊
