### ISSUE TITLE
大佬大佬，有考虑适配一下uni-app吗

### ISSUE THREAD

**Issue by AaaaaaaHu** [deepkolos/platformize#18]
大佬大佬，有考虑适配一下uni-app吗，我直接把你微信小程序的oasis、tests-oasis文件放到uni-app项目内，在运行到微信小程序的话没问题。但是当点击渲染的时候会报错，并且页面内的其他方法（比如：点击'示例‘，无法弹窗、无法修改），也会报同样的问题。根本不知道哪里有问题呀。。。呜呜呜。。
![123](https://user-images.githubusercontent.com/66403010/196611196-a9ef81e6-8975-400f-8013-ddf57e47f3ca.png)

**Comment by deepkolos** [comment]
@AaaaaaaHu 不能复制代码的方式, 需要额外的构建, 具体参考下文档 或者 simple
