### ISSUE TITLE
今日头条APP小程序无法打开“字节小程序 DEMO”，抖音可以

### ISSUE THREAD

**Issue by elliottssu** [deepkolos/platformize#19]
可以测试一下，无法在今日头条APP打开预览，抖音APP可以，这个是什么原因

**Comment by deepkolos** [comment]
我只测试了抖音, 后面有空debug下

**Comment by deepkolos** [comment]
@elliottssu 我这边刚测试是OK的


https://user-images.githubusercontent.com/12824616/221127856-51658e3f-9e4b-4d32-9c34-ad2f5b62b097.mp4

**Comment by deepkolos** [comment]
@elliottssu 刚新增的oasis, pixi 都是能跑的, 可以再试试

https://user-images.githubusercontent.com/12824616/221128893-97596216-9b4d-4f21-8e05-a18f893c3210.mp4


https://user-images.githubusercontent.com/12824616/221128934-b595a6e9-31ff-4034-b7a9-84add4c8818b.mp4
