### ISSUE TITLE
pixi 真机不显示 text，也不响应点击事件

### ISSUE THREAD

**Issue by seekcx** [deepkolos/platformize#3]
复现代码：

```typescript
// pixi.ts
import * as PIXI from '@pixi/core';
export * from '@pixi/core';
export * from '@pixi/text';
export * from '@pixi/events';
import { TickerPlugin } from '@pixi/ticker';
import { install } from '@pixi/unsafe-eval';
import { Application } from '@pixi/app';
import { Renderer, BatchRenderer } from '@pixi/core';
import { InteractionManager } from '@pixi/interaction';

function initializePixi() {
  // 注册插件
  install(PIXI);
  Application.registerPlugin(TickerPlugin);
  Renderer.registerPlugin('batch', BatchRenderer);
  Renderer.registerPlugin('interaction', InteractionManager);
}

/**
 * 创建 Pixi 应用
 *
 * @param canvas 画板
 * @returns 应用
 */
export function createApplication(canvas: any) {
  initializePixi();

  const app = new Application({
    view: canvas,
    width: canvas.width,
    height: canvas.height,
    backgroundColor: 0xffffff,
    antialias: true,
    resolution: window.devicePixelRatio,
  });

  return app;
}
```
```typescript
// game.ts

import * as Pixi from './pixi';
import { Text } from '@pixi/text';
import { Graphics } from '@pixi/graphics';
import { WechatGamePlatform, PlatformManager } from 'platformize-pixi';

// 微信小游戏适配层
const canvas: any = wx.createCanvas();
const platform = new WechatGamePlatform(canvas);
PlatformManager.set(platform);
platform.init(Pixi, wx.createCanvas());

const app = Pixi.createApplication(canvas);

const textSprite = new Text('Hello, world!');
textSprite.position.set(100, 100);
app.stage.addChild(textSprite);

const boxSprite = new Graphics()
  .beginFill(0x00aaaa)
  .drawRect(50, 150, 250, 250)
  .endFill();
boxSprite.interactive = true;
boxSprite.on('pointerdown', () => {
  wx.showToast({ title: 'pointerdown' });
});
app.stage.addChild(boxSprite);
```

开发工具渲染结果：

<img width="346" alt="image" src="https://user-images.githubusercontent.com/8244814/160264947-53855a57-2fd3-4a45-9ea6-05a4935731e6.png">

真机渲染结果：
![281648350362_ pic](https://user-images.githubusercontent.com/8244814/160264942-f2d6f7c3-6db1-474f-ad96-9d6384581483.jpg)

开发工具点击方块：
<img width="336" alt="image" src="https://user-images.githubusercontent.com/8244814/160264967-a8be5327-3122-4f3c-b6ea-4f741bf57de2.png">

真机点击没有任何反应，控制台也没有报错：
![291648350365_ pic](https://user-images.githubusercontent.com/8244814/160264974-ac5663c0-e93f-4329-a0ab-6e46189b6e6a.jpg)

**Comment by deepkolos** [comment]
@seekcx 应该是可以的, 只是依赖小游戏canvas 2d 绘制text的能力, 点击的问题注意下使用的版本是否为最新的`platformize-pixi@6.2.2` pixi版本是否为: `@pixi/core@6.2.1`

实例可以参考这个 pixi 微信小游戏demo

https://github.com/deepkolos/platformize/tree/main/examples/pixi-wechat-game

真机运行效果

![origin_img_v2_bffaf387-e25d-491f-90f2-d24953630e5g](https://user-images.githubusercontent.com/12824616/160275021-e02aea37-0f33-452a-8446-ba99d6a2de08.jpg)

模拟器

<img width="379" alt="image" src="https://user-images.githubusercontent.com/12824616/160275032-cfe6f99a-8ed8-4731-b540-b8797aac8f83.png">

小程序真机

![origin_img_v2_40926b89-b5c8-4a0f-b2f4-3659aba0a2cg](https://user-images.githubusercontent.com/12824616/160275174-95c9c09c-5c59-4102-9277-b29bb30b3641.jpg)

**Comment by deepkolos** [comment]
@seekcx 关于所提供的代码, 我这边的测试结果

![origin_img_v2_41cf06c4-d1be-44ea-a1db-806feb4e3f5g](https://user-images.githubusercontent.com/12824616/160275520-65535058-69f3-4474-85c9-b6d296399315.jpg)

基于https://github.com/deepkolos/platformize/tree/main/examples/pixi-wechat-game

<img width="924" alt="image" src="https://user-images.githubusercontent.com/12824616/160275550-92e63259-4d04-4cc0-99b7-d2edcd6a1e71.png">


```ts
// text.ts
import * as PIXI from './pixi';

export function HelloWorldText(canvas) {
  PIXI.__init__();

  const app = new PIXI.Application({
    view: canvas,
    width: canvas.width,
    height: canvas.height,
    backgroundColor: 0xffffff,
    antialias: true,
    resolution: window.devicePixelRatio,
  });

  const textSprite = new PIXI.Text('Hello, world!');
  textSprite.position.set(100, 100);
  app.stage.addChild(textSprite);

  const boxSprite = new PIXI.Graphics().beginFill(0x00aaaa).drawRect(50, 150, 250, 250).endFill();
  boxSprite.interactive = true;
  boxSprite.on('pointerdown', () => {
    wx.showToast({ title: 'pointerdown' });
  });
  app.stage.addChild(boxSprite);

  return app;
}
```

**Comment by seekcx** [comment]
是不是系统的原因？我测试的机器是ios。

在我这 example 打开是这个样子，无法正常运行：
![311648390000_ pic](https://user-images.githubusercontent.com/8244814/160285461-2ddbca27-4147-4b43-a17b-28973923ffc5.jpg)

使用 example 改的 demo，运行状况和我前面描述的一样，文字不显示，事件不响应。

**Comment by seekcx** [comment]
我测试用的版本是6.2.2，example 用的版本是 6.2.1

**Comment by deepkolos** [comment]
@seekcx  我这边没有IOS测试机, 估计是系统问题了, 或者说没适配到的系统问题

**Comment by seekcx** [comment]
由于ios无法调试，我在 EventTarget 里加了一些console.log，发现ios上触发的事件名称比较奇葩，比如 touchstart，在 ios 上触发出来的名字叫 ontouchstart，这里看怎么兼容一下，我写了一小段兼容代码在ios上成功响应了事件（图2），但是没考虑其它地方的 break change 问题。

<img width="490" alt="image" src="https://user-images.githubusercontent.com/8244814/160968766-67d3ba0a-ff60-4175-a269-34d4a912001a.png">
<img width="782" alt="image" src="https://user-images.githubusercontent.com/8244814/160968802-2028fa36-6d4f-4017-9472-b98b229c5a2d.png">
<img width="446" alt="image" src="https://user-images.githubusercontent.com/8244814/160968887-524816e7-c6d5-4f3d-a2e8-4fb51f1d4fd4.png">
