### ISSUE TITLE
platformize-three/dist-plugin

### ISSUE THREAD

**Issue by Evseiy** [deepkolos/platformize#30]
platformize-three/dist-plugin这个文件没有吗？

**Comment by deepkolos** [comment]
@jtabibito 本地的话需要构建下 rush build

npm包是有的
https://www.npmjs.com/package/platformize-three?activeTab=code

<img width="936" alt="image" src="https://github.com/deepkolos/platformize/assets/12824616/878b1a8c-be09-4596-8eee-4c0d01e7b795">
