### ISSUE TITLE
three-wechat项目依赖安装失败

### ISSUE THREAD

**Issue by 0x3f97** [deepkolos/platformize#7]
readPackage hook is declared. Manifests of dependencies might get overridden
 WARN  GET https://registry.npmjs.org/ws/-/ws-6.2.3.tgz error (ERR_PNPM_FETCH_404). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npmjs.org/ws/-/ws-6.2.3.tgz error (ERR_PNPM_FETCH_404). Will retry in 1 minute. 1 retries left.
 ERROR  GET https://registry.npmjs.org/ws/-/ws-6.2.3.tgz: Not Found - 404
![image](https://user-images.githubusercontent.com/32476377/174442378-f8105245-153e-45d6-9e47-fbe577914fb7.png)

提示说这个包找不到

**Comment by deepkolos** [comment]
@0x3f97 已修复 手动删除pnpm-lock.yml再rush update
