### ISSUE TITLE
plaformize-three淘宝小程序兼容模拟器问题

### ISSUE THREAD

**Issue by weilaiqishi** [deepkolos/platformize#8]
有两处代码影响了淘宝小程序模拟器运行

1.在platformize/src/taoba/index.ts中

```js
    canvas.getContext = function getContext() {
      if (arguments[0] !== 'webgl') return null;
      // @ts-ignore
      return canvas._getContext(...arguments);
    };
```

这里的赋值操作会报错，重写canvas.getContext方法的作用是啥？

2.在platformize/src/taobao/XMLHttpRequest.ts

```js
  async send(data = '') {
   ...
  }
```

这里的async经过打包会使用 regenerator-runtime，这个包里面的 `Function("r", "regeneratorRuntime = r")(runtime);` 在模拟器上会报错。那么swc不去处理`async await`是否会好一点?

**Comment by deepkolos** [comment]
@weilaiqishi 
1. 之前适配的时候应该是从wechat复制过来
2. 我看看swc文档
