### ISSUE TITLE
可以在Taro中使用吗

### ISSUE THREAD

**Issue by shuaigeek** [deepkolos/platformize#9]
你好，我最近在做一个微信小程序的项目，使用了Taro框架，项目中需要展示三维模型，看到了作者的开源项目，感觉很好用，我想问一下，可以在Taro中使用吗，该如何配置。谢谢。

**Comment by deepkolos** [comment]
需要加额外构建逻辑

**Comment by alphasen** [comment]
给提供下思路，都需要考虑哪些配置啊

**Comment by deepkolos** [comment]
@shuaigeek 如果taro 也是 rollup构建的话 可以参考下这个配置, 如果不是估计单独建个构建rollup配置

rollup 使用了threejs的index.ts 产出 index.js 然后再走taro构建 

https://github.com/deepkolos/platformize/blob/main/examples/playcanvas-wechat-simple/rollup.config.js

**Comment by Runc2333** [comment]
我写了一个Taro的示例，可以参考一下
https://github.com/Runc2333/platformize-three-taro-demo
